version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = false
rainCulling = true
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 16
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 2.0
leavesCullingMode = "DEFAULT"
leavesCullingAmount = 2
includeMangroveRoots = false
powderSnowCulling = true
endGatewayCulling = false
beaconBeamCulling = false
entityModelCulling = false
useOnModdedBlocksByDefault = true

[modCompatibility]
azurelib = true
naturalist = true
farmersdelight = true
lightmanscurrency = true
doapi = true
paladins = true
culturaldelights = true
brewery = true
create = true
farm_and_charm = true
oceansdelight = true
brewinandchewin = true
yungscavebiomes = true
refurbished_furniture = true
runes = true
rogues = true
copycats = false
minecraft = true
lootr = true
ends_delight = true
createdieselgenerators = true
createdeco = true
yigd = true
sophisticatedstorage = true
nethervinery = true
railways = true
easy_npc = true
jewelry = true
milk = true
waystones = true
archers = true
mynethersdelight = true
herbalbrews = true
bakery = true
vinery = true
sophisticatedbackpacks = true
treechop = true
expandeddelight = true
exposure = true
spell_engine = true
